version: '3'

services:
  web:
    build: .
    env_file:
      - .env
    command: sh -c "python manage.py migrate"
#    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    volumes:
      - .:/Shop
      - static_volume:/Shop/staticfiles
      - media_volume:/Shop/mediafiles
    ports:
      - "8021:8000"
    depends_on:
      - shop_db
#      - redis
    restart: always

  shop_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user_shop
      POSTGRES_PASSWORD: password_shop
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


#  redis:
#    image: redis:alpine
#    ports:
#      - "6372:6379"
#    volumes:
#      - redis_data:/data
#    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
#  redis_data:
