# Generated by Django 5.2.7 on 2025-11-05 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_buyrequest_buyrequestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='currency',
            field=models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Foydalanuvchi bilan bog'lanish uchun telefon raqami", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam +998xxxxxxxxx yoki shunga o'xshash formatda bo'lishi kerak.", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
